const link = 'www.link.com';
// eslint-disable-next-line @typescript-eslint/naming-convention
const data_publicacao = '20/01/2024 12:00:00';

export const dataAllNews = { items: [
  {
    id: 1,
    tipo: 'Notícia',
    titulo: 'Teste 1',
    introducao: 'Teste dataAllNews 1',
    data_publicacao,
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link,
  },
  {
    id: 2,
    tipo: 'Notícia',
    titulo: 'Teste 2',
    introducao: 'Teste dataAllNews 2',
    data_publicacao,
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link,
  },
  {
    id: 3,
    tipo: 'Release',
    titulo: 'Teste 3',
    introducao: 'Teste dataAllNews 3',
    data_publicacao,
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link,
  },
  {
    id: 4,
    tipo: 'Notícia',
    titulo: 'Teste 4',
    introducao: 'Teste dataAllNews 4',
    data_publicacao,
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link,
  },
  {
    id: 5,
    tipo: 'Release',
    titulo: 'Teste 5',
    introducao: 'Teste dataAllNews 5',
    data_publicacao,
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link,
  }],
};

export const dataNews = { items: [
  {
    id: 1,
    tipo: 'Notícia',
    titulo: 'Teste 1',
    introducao: 'Teste dataNews 1',
    data_publicacao,
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link,
  },
  {
    id: 2,
    tipo: 'Notícia',
    titulo: 'Teste 2',
    introducao: 'Teste dataNews 2',
    data_publicacao,
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link,
  },
  {
    id: 3,
    tipo: 'Notícia',
    titulo: 'Teste 3',
    introducao: 'Teste dataNews 3',
    data_publicacao,
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link,
  },
  {
    id: 4,
    tipo: 'Notícia',
    titulo: 'Teste 4',
    introducao: 'Teste dataNews 4',
    data_publicacao,
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link,
  },
  {
    id: 5,
    tipo: 'Notícia',
    titulo: 'Teste 5',
    introducao: 'Teste dataNews 5',
    data_publicacao,
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link,
  }],
};

export const dataRelease = { items: [
  {
    id: 1,
    tipo: 'Release',
    titulo: 'Teste 1',
    introducao: 'Teste dataRelease 1',
    data_publicacao,
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link,
  },
  {
    id: 2,
    tipo: 'Release',
    titulo: 'Teste 2',
    introducao: 'Teste dataRelease 2',
    data_publicacao,
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link,
  },
  {
    id: 3,
    tipo: 'Release',
    titulo: 'Teste 3',
    introducao: 'Teste dataRelease 3',
    data_publicacao,
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link,
  },
  {
    id: 4,
    tipo: 'Release',
    titulo: 'Teste 4',
    introducao: 'Teste dataRelease 4',
    data_publicacao,
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link,
  },
  {
    id: 5,
    tipo: 'Release',
    titulo: 'Teste 5',
    introducao: 'Teste dataRelease 5',
    data_publicacao: '19/01/2024 09:00:00',
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link,
  }],
};
