export const dataAllNews = { items: [
  {
    id: 1,
    tipo: 'Notícia',
    titulo: 'Teste 1',
    introducao: 'Teste introducao 1',
    data_publicacao: '19/01/2024 09:00:00',
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link: 'www.link.com',
  },
  {
    id: 2,
    tipo: 'Notícia',
    titulo: 'Teste 2',
    introducao: 'Teste introducao 2',
    data_publicacao: '19/01/2024 09:00:00',
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link: 'www.link.com',
  },
  {
    id: 3,
    tipo: 'Release',
    titulo: 'Teste 3',
    introducao: 'Teste introducao 3',
    data_publicacao: '19/01/2024 09:00:00',
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link: 'www.link.com',
  },
  {
    id: 4,
    tipo: 'Notícia',
    titulo: 'Teste 4',
    introducao: 'Teste introducao 4',
    data_publicacao: '19/01/2024 09:00:00',
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link: 'www.link.com',
  },
  {
    id: 5,
    tipo: 'Release',
    titulo: 'Teste 5',
    introducao: 'Teste introducao 5',
    data_publicacao: '19/01/2024 09:00:00',
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link: 'www.link.com',
  }],
};

export const dataNews = { items: [
  {
    id: 1,
    tipo: 'Notícia',
    titulo: 'Teste 1',
    introducao: 'Teste introducao 1',
    data_publicacao: '19/01/2024 09:00:00',
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link: 'www.link.com',
  },
  {
    id: 2,
    tipo: 'Notícia',
    titulo: 'Teste 2',
    introducao: 'Teste introducao 2',
    data_publicacao: '19/01/2024 09:00:00',
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link: 'www.link.com',
  },
  {
    id: 3,
    tipo: 'Notícia',
    titulo: 'Teste 3',
    introducao: 'Teste introducao 3',
    data_publicacao: '19/01/2024 09:00:00',
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link: 'www.link.com',
  },
  {
    id: 4,
    tipo: 'Notícia',
    titulo: 'Teste 4',
    introducao: 'Teste introducao 4',
    data_publicacao: '19/01/2024 09:00:00',
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link: 'www.link.com',
  },
  {
    id: 5,
    tipo: 'Notícia',
    titulo: 'Teste 5',
    introducao: 'Teste introducao 5',
    data_publicacao: '19/01/2024 09:00:00',
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link: 'www.link.com',
  }],
};

export const dataRelease = { items: [
  {
    id: 1,
    tipo: 'Release',
    titulo: 'Teste 1',
    introducao: 'Teste introducao 1',
    data_publicacao: '19/01/2024 09:00:00',
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link: 'www.link.com',
  },
  {
    id: 2,
    tipo: 'Release',
    titulo: 'Teste 2',
    introducao: 'Teste introducao 2',
    data_publicacao: '19/01/2024 09:00:00',
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link: 'www.link.com',
  },
  {
    id: 3,
    tipo: 'Release',
    titulo: 'Teste 3',
    introducao: 'Teste introducao 3',
    data_publicacao: '19/01/2024 09:00:00',
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link: 'www.link.com',
  },
  {
    id: 4,
    tipo: 'Release',
    titulo: 'Teste 4',
    introducao: 'Teste introducao 4',
    data_publicacao: '19/01/2024 09:00:00',
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link: 'www.link.com',
  },
  {
    id: 5,
    tipo: 'Release',
    titulo: 'Teste 5',
    introducao: 'Teste introducao 5',
    data_publicacao: '19/01/2024 09:00:00',
    produto_id: 0,
    produtos: '',
    editorias: 'ibge',
    produtos_relacionados: '',
    destaque: true,
    link: 'www.link.com',
  }],
};
